//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManagement.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad user name or password..
        /// </summary>
        public static string BadUserOrPassword {
            get {
                return ResourceManager.GetString("BadUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel any changes, are you sure?.
        /// </summary>
        public static string CancelAnyChangesMessageBoxText {
            get {
                return ResourceManager.GetString("CancelAnyChangesMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel editing current commodity, are you sure?.
        /// </summary>
        public static string CancelCurrentCommodityMessageBoxText {
            get {
                return ResourceManager.GetString("CancelCurrentCommodityMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel editing current job, are you sure?.
        /// </summary>
        public static string CancelCurrentJobMessageBoxText {
            get {
                return ResourceManager.GetString("CancelCurrentJobMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel editing current user, are you sure?.
        /// </summary>
        public static string CancelCurrentUserMessageBoxText {
            get {
                return ResourceManager.GetString("CancelCurrentUserMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel editing current vendor, are you sure?.
        /// </summary>
        public static string CancelCurrentVendorMessageBoxText {
            get {
                return ResourceManager.GetString("CancelCurrentVendorMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        public static string ConfirmMessageBoxCaption {
            get {
                return ResourceManager.GetString("ConfirmMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current user, are you sure?.
        /// </summary>
        public static string DeleteCurrentUserMessageBoxText {
            get {
                return ResourceManager.GetString("DeleteCurrentUserMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfileSavedCaption {
            get {
                return ResourceManager.GetString("MyProfileSavedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile is saved successfully..
        /// </summary>
        public static string MyProfileSavedText {
            get {
                return ResourceManager.GetString("MyProfileSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        public static string NewJobCreatedCaption {
            get {
                return ResourceManager.GetString("NewJobCreatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New job created with job ID : .
        /// </summary>
        public static string NewJobCreatedText {
            get {
                return ResourceManager.GetString("NewJobCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found..
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Maintenance Error.
        /// </summary>
        public static string UserMaintenanceErrorCaption {
            get {
                return ResourceManager.GetString("UserMaintenanceErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Maintenance.
        /// </summary>
        public static string UserMaintenanceUpdatedCaption {
            get {
                return ResourceManager.GetString("UserMaintenanceUpdatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information updated successfully..
        /// </summary>
        public static string UserMaintenanceUpdatedText {
            get {
                return ResourceManager.GetString("UserMaintenanceUpdatedText", resourceCulture);
            }
        }
    }
}
