//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InventoryManagementModel", "FK__Commodity__Inven__22AA2996", "CommodityType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InventoryManagement.Data.Web.CommodityType), "Commodity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InventoryManagement.Data.Web.Commodity), true)]
[assembly: EdmRelationshipAttribute("InventoryManagementModel", "FK__Commodity__UnitO__239E4DCF", "UnitOfMeasure", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InventoryManagement.Data.Web.UnitOfMeasure), "Commodity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InventoryManagement.Data.Web.Commodity), true)]
[assembly: EdmRelationshipAttribute("InventoryManagementModel", "FK__Commodity__Vendo__24927208", "Vendor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InventoryManagement.Data.Web.Vendor), "Commodity", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InventoryManagement.Data.Web.Commodity), true)]
[assembly: EdmRelationshipAttribute("InventoryManagementModel", "FK__Vendor__MeansOfP__15502E78", "MeansOfPayment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InventoryManagement.Data.Web.MeansOfPayment), "Vendor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InventoryManagement.Data.Web.Vendor), true)]

#endregion

namespace InventoryManagement.Data.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InventoryManagementEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InventoryManagementEntities object using the connection string found in the 'InventoryManagementEntities' section of the application configuration file.
        /// </summary>
        public InventoryManagementEntities() : base("name=InventoryManagementEntities", "InventoryManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventoryManagementEntities object.
        /// </summary>
        public InventoryManagementEntities(string connectionString) : base(connectionString, "InventoryManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventoryManagementEntities object.
        /// </summary>
        public InventoryManagementEntities(EntityConnection connection) : base(connection, "InventoryManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Commodity> Commodities
        {
            get
            {
                if ((_Commodities == null))
                {
                    _Commodities = base.CreateObjectSet<Commodity>("Commodities");
                }
                return _Commodities;
            }
        }
        private ObjectSet<Commodity> _Commodities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CommodityType> CommodityTypes
        {
            get
            {
                if ((_CommodityTypes == null))
                {
                    _CommodityTypes = base.CreateObjectSet<CommodityType>("CommodityTypes");
                }
                return _CommodityTypes;
            }
        }
        private ObjectSet<CommodityType> _CommodityTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MeansOfPayment> MeansOfPayments
        {
            get
            {
                if ((_MeansOfPayments == null))
                {
                    _MeansOfPayments = base.CreateObjectSet<MeansOfPayment>("MeansOfPayments");
                }
                return _MeansOfPayments;
            }
        }
        private ObjectSet<MeansOfPayment> _MeansOfPayments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UnitOfMeasure> UnitOfMeasures
        {
            get
            {
                if ((_UnitOfMeasures == null))
                {
                    _UnitOfMeasures = base.CreateObjectSet<UnitOfMeasure>("UnitOfMeasures");
                }
                return _UnitOfMeasures;
            }
        }
        private ObjectSet<UnitOfMeasure> _UnitOfMeasures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vendor> Vendors
        {
            get
            {
                if ((_Vendors == null))
                {
                    _Vendors = base.CreateObjectSet<Vendor>("Vendors");
                }
                return _Vendors;
            }
        }
        private ObjectSet<Vendor> _Vendors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkOrder> WorkOrders
        {
            get
            {
                if ((_WorkOrders == null))
                {
                    _WorkOrders = base.CreateObjectSet<WorkOrder>("WorkOrders");
                }
                return _WorkOrders;
            }
        }
        private ObjectSet<WorkOrder> _WorkOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Commodities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommodities(Commodity commodity)
        {
            base.AddObject("Commodities", commodity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CommodityTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommodityTypes(CommodityType commodityType)
        {
            base.AddObject("CommodityTypes", commodityType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MeansOfPayments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeansOfPayments(MeansOfPayment meansOfPayment)
        {
            base.AddObject("MeansOfPayments", meansOfPayment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UnitOfMeasures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUnitOfMeasures(UnitOfMeasure unitOfMeasure)
        {
            base.AddObject("UnitOfMeasures", unitOfMeasure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vendors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVendors(Vendor vendor)
        {
            base.AddObject("Vendors", vendor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkOrders(WorkOrder workOrder)
        {
            base.AddObject("WorkOrders", workOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventoryManagementModel", Name="Commodity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commodity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Commodity object.
        /// </summary>
        /// <param name="inventoryID">Initial value of the InventoryID property.</param>
        /// <param name="partNumber">Initial value of the PartNumber property.</param>
        /// <param name="inventoryType">Initial value of the InventoryType property.</param>
        /// <param name="partDescription">Initial value of the PartDescription property.</param>
        /// <param name="unitOfMeasureID">Initial value of the UnitOfMeasureID property.</param>
        /// <param name="reorderLevel">Initial value of the ReorderLevel property.</param>
        /// <param name="vendor">Initial value of the Vendor property.</param>
        /// <param name="discontinued">Initial value of the Discontinued property.</param>
        public static Commodity CreateCommodity(global::System.Int32 inventoryID, global::System.String partNumber, global::System.Int32 inventoryType, global::System.String partDescription, global::System.Byte unitOfMeasureID, global::System.Int32 reorderLevel, global::System.Int32 vendor, global::System.Boolean discontinued)
        {
            Commodity commodity = new Commodity();
            commodity.InventoryID = inventoryID;
            commodity.PartNumber = partNumber;
            commodity.InventoryType = inventoryType;
            commodity.PartDescription = partDescription;
            commodity.UnitOfMeasureID = unitOfMeasureID;
            commodity.ReorderLevel = reorderLevel;
            commodity.Vendor = vendor;
            commodity.Discontinued = discontinued;
            return commodity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InventoryID
        {
            get
            {
                return _InventoryID;
            }
            set
            {
                if (_InventoryID != value)
                {
                    OnInventoryIDChanging(value);
                    ReportPropertyChanging("InventoryID");
                    _InventoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InventoryID");
                    OnInventoryIDChanged();
                }
            }
        }
        private global::System.Int32 _InventoryID;
        partial void OnInventoryIDChanging(global::System.Int32 value);
        partial void OnInventoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PartNumber
        {
            get
            {
                return _PartNumber;
            }
            set
            {
                OnPartNumberChanging(value);
                ReportPropertyChanging("PartNumber");
                _PartNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PartNumber");
                OnPartNumberChanged();
            }
        }
        private global::System.String _PartNumber;
        partial void OnPartNumberChanging(global::System.String value);
        partial void OnPartNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InventoryType
        {
            get
            {
                return _InventoryType;
            }
            set
            {
                OnInventoryTypeChanging(value);
                ReportPropertyChanging("InventoryType");
                _InventoryType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InventoryType");
                OnInventoryTypeChanged();
            }
        }
        private global::System.Int32 _InventoryType;
        partial void OnInventoryTypeChanging(global::System.Int32 value);
        partial void OnInventoryTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PartDescription
        {
            get
            {
                return _PartDescription;
            }
            set
            {
                OnPartDescriptionChanging(value);
                ReportPropertyChanging("PartDescription");
                _PartDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PartDescription");
                OnPartDescriptionChanged();
            }
        }
        private global::System.String _PartDescription;
        partial void OnPartDescriptionChanging(global::System.String value);
        partial void OnPartDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte UnitOfMeasureID
        {
            get
            {
                return _UnitOfMeasureID;
            }
            set
            {
                OnUnitOfMeasureIDChanging(value);
                ReportPropertyChanging("UnitOfMeasureID");
                _UnitOfMeasureID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitOfMeasureID");
                OnUnitOfMeasureIDChanged();
            }
        }
        private global::System.Byte _UnitOfMeasureID;
        partial void OnUnitOfMeasureIDChanging(global::System.Byte value);
        partial void OnUnitOfMeasureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReorderLevel
        {
            get
            {
                return _ReorderLevel;
            }
            set
            {
                OnReorderLevelChanging(value);
                ReportPropertyChanging("ReorderLevel");
                _ReorderLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReorderLevel");
                OnReorderLevelChanged();
            }
        }
        private global::System.Int32 _ReorderLevel;
        partial void OnReorderLevelChanging(global::System.Int32 value);
        partial void OnReorderLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Vendor
        {
            get
            {
                return _Vendor;
            }
            set
            {
                OnVendorChanging(value);
                ReportPropertyChanging("Vendor");
                _Vendor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vendor");
                OnVendorChanged();
            }
        }
        private global::System.Int32 _Vendor;
        partial void OnVendorChanging(global::System.Int32 value);
        partial void OnVendorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Discontinued
        {
            get
            {
                return _Discontinued;
            }
            set
            {
                OnDiscontinuedChanging(value);
                ReportPropertyChanging("Discontinued");
                _Discontinued = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discontinued");
                OnDiscontinuedChanged();
            }
        }
        private global::System.Boolean _Discontinued;
        partial void OnDiscontinuedChanging(global::System.Boolean value);
        partial void OnDiscontinuedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Commodity__Inven__22AA2996", "CommodityType")]
        public CommodityType CommodityType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommodityType>("InventoryManagementModel.FK__Commodity__Inven__22AA2996", "CommodityType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommodityType>("InventoryManagementModel.FK__Commodity__Inven__22AA2996", "CommodityType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CommodityType> CommodityTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommodityType>("InventoryManagementModel.FK__Commodity__Inven__22AA2996", "CommodityType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CommodityType>("InventoryManagementModel.FK__Commodity__Inven__22AA2996", "CommodityType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Commodity__UnitO__239E4DCF", "UnitOfMeasure")]
        public UnitOfMeasure UnitOfMeasure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UnitOfMeasure>("InventoryManagementModel.FK__Commodity__UnitO__239E4DCF", "UnitOfMeasure").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UnitOfMeasure>("InventoryManagementModel.FK__Commodity__UnitO__239E4DCF", "UnitOfMeasure").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UnitOfMeasure> UnitOfMeasureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UnitOfMeasure>("InventoryManagementModel.FK__Commodity__UnitO__239E4DCF", "UnitOfMeasure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UnitOfMeasure>("InventoryManagementModel.FK__Commodity__UnitO__239E4DCF", "UnitOfMeasure", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Commodity__Vendo__24927208", "Vendor")]
        public Vendor Vendor1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("InventoryManagementModel.FK__Commodity__Vendo__24927208", "Vendor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("InventoryManagementModel.FK__Commodity__Vendo__24927208", "Vendor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vendor> Vendor1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("InventoryManagementModel.FK__Commodity__Vendo__24927208", "Vendor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vendor>("InventoryManagementModel.FK__Commodity__Vendo__24927208", "Vendor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventoryManagementModel", Name="CommodityType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommodityType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CommodityType object.
        /// </summary>
        /// <param name="typeID">Initial value of the TypeID property.</param>
        /// <param name="typeCode">Initial value of the TypeCode property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static CommodityType CreateCommodityType(global::System.Int32 typeID, global::System.String typeCode, global::System.String description)
        {
            CommodityType commodityType = new CommodityType();
            commodityType.TypeID = typeID;
            commodityType.TypeCode = typeCode;
            commodityType.Description = description;
            return commodityType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TypeID
        {
            get
            {
                return _TypeID;
            }
            set
            {
                if (_TypeID != value)
                {
                    OnTypeIDChanging(value);
                    ReportPropertyChanging("TypeID");
                    _TypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TypeID");
                    OnTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _TypeID;
        partial void OnTypeIDChanging(global::System.Int32 value);
        partial void OnTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TypeCode
        {
            get
            {
                return _TypeCode;
            }
            set
            {
                OnTypeCodeChanging(value);
                ReportPropertyChanging("TypeCode");
                _TypeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TypeCode");
                OnTypeCodeChanged();
            }
        }
        private global::System.String _TypeCode;
        partial void OnTypeCodeChanging(global::System.String value);
        partial void OnTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Commodity__Inven__22AA2996", "Commodity")]
        public EntityCollection<Commodity> Commodities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commodity>("InventoryManagementModel.FK__Commodity__Inven__22AA2996", "Commodity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commodity>("InventoryManagementModel.FK__Commodity__Inven__22AA2996", "Commodity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventoryManagementModel", Name="MeansOfPayment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MeansOfPayment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MeansOfPayment object.
        /// </summary>
        /// <param name="paymentMethodID">Initial value of the PaymentMethodID property.</param>
        /// <param name="paymentType">Initial value of the PaymentType property.</param>
        public static MeansOfPayment CreateMeansOfPayment(global::System.Int32 paymentMethodID, global::System.String paymentType)
        {
            MeansOfPayment meansOfPayment = new MeansOfPayment();
            meansOfPayment.PaymentMethodID = paymentMethodID;
            meansOfPayment.PaymentType = paymentType;
            return meansOfPayment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaymentMethodID
        {
            get
            {
                return _PaymentMethodID;
            }
            set
            {
                if (_PaymentMethodID != value)
                {
                    OnPaymentMethodIDChanging(value);
                    ReportPropertyChanging("PaymentMethodID");
                    _PaymentMethodID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaymentMethodID");
                    OnPaymentMethodIDChanged();
                }
            }
        }
        private global::System.Int32 _PaymentMethodID;
        partial void OnPaymentMethodIDChanging(global::System.Int32 value);
        partial void OnPaymentMethodIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PaymentType
        {
            get
            {
                return _PaymentType;
            }
            set
            {
                OnPaymentTypeChanging(value);
                ReportPropertyChanging("PaymentType");
                _PaymentType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PaymentType");
                OnPaymentTypeChanged();
            }
        }
        private global::System.String _PaymentType;
        partial void OnPaymentTypeChanging(global::System.String value);
        partial void OnPaymentTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Vendor__MeansOfP__15502E78", "Vendor")]
        public EntityCollection<Vendor> Vendors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Vendor>("InventoryManagementModel.FK__Vendor__MeansOfP__15502E78", "Vendor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Vendor>("InventoryManagementModel.FK__Vendor__MeansOfP__15502E78", "Vendor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventoryManagementModel", Name="UnitOfMeasure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UnitOfMeasure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UnitOfMeasure object.
        /// </summary>
        /// <param name="unitOfMeasureID">Initial value of the UnitOfMeasureID property.</param>
        /// <param name="unitOfMeasureTag">Initial value of the UnitOfMeasureTag property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static UnitOfMeasure CreateUnitOfMeasure(global::System.Byte unitOfMeasureID, global::System.String unitOfMeasureTag, global::System.String description)
        {
            UnitOfMeasure unitOfMeasure = new UnitOfMeasure();
            unitOfMeasure.UnitOfMeasureID = unitOfMeasureID;
            unitOfMeasure.UnitOfMeasureTag = unitOfMeasureTag;
            unitOfMeasure.Description = description;
            return unitOfMeasure;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte UnitOfMeasureID
        {
            get
            {
                return _UnitOfMeasureID;
            }
            set
            {
                if (_UnitOfMeasureID != value)
                {
                    OnUnitOfMeasureIDChanging(value);
                    ReportPropertyChanging("UnitOfMeasureID");
                    _UnitOfMeasureID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UnitOfMeasureID");
                    OnUnitOfMeasureIDChanged();
                }
            }
        }
        private global::System.Byte _UnitOfMeasureID;
        partial void OnUnitOfMeasureIDChanging(global::System.Byte value);
        partial void OnUnitOfMeasureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UnitOfMeasureTag
        {
            get
            {
                return _UnitOfMeasureTag;
            }
            set
            {
                OnUnitOfMeasureTagChanging(value);
                ReportPropertyChanging("UnitOfMeasureTag");
                _UnitOfMeasureTag = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UnitOfMeasureTag");
                OnUnitOfMeasureTagChanged();
            }
        }
        private global::System.String _UnitOfMeasureTag;
        partial void OnUnitOfMeasureTagChanging(global::System.String value);
        partial void OnUnitOfMeasureTagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Commodity__UnitO__239E4DCF", "Commodity")]
        public EntityCollection<Commodity> Commodities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commodity>("InventoryManagementModel.FK__Commodity__UnitO__239E4DCF", "Commodity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commodity>("InventoryManagementModel.FK__Commodity__UnitO__239E4DCF", "Commodity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventoryManagementModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static User CreateUser(global::System.Int32 userID)
        {
            User user = new User();
            user.UserID = userID;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordHash
        {
            get
            {
                return _PasswordHash;
            }
            set
            {
                OnPasswordHashChanging(value);
                ReportPropertyChanging("PasswordHash");
                _PasswordHash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordHash");
                OnPasswordHashChanged();
            }
        }
        private global::System.String _PasswordHash;
        partial void OnPasswordHashChanging(global::System.String value);
        partial void OnPasswordHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordSalt
        {
            get
            {
                return _PasswordSalt;
            }
            set
            {
                OnPasswordSaltChanging(value);
                ReportPropertyChanging("PasswordSalt");
                _PasswordSalt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordSalt");
                OnPasswordSaltChanged();
            }
        }
        private global::System.String _PasswordSalt;
        partial void OnPasswordSaltChanging(global::System.String value);
        partial void OnPasswordSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordQuestion
        {
            get
            {
                return _PasswordQuestion;
            }
            set
            {
                OnPasswordQuestionChanging(value);
                ReportPropertyChanging("PasswordQuestion");
                _PasswordQuestion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordQuestion");
                OnPasswordQuestionChanged();
            }
        }
        private global::System.String _PasswordQuestion;
        partial void OnPasswordQuestionChanging(global::System.String value);
        partial void OnPasswordQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordAnswerHash
        {
            get
            {
                return _PasswordAnswerHash;
            }
            set
            {
                OnPasswordAnswerHashChanging(value);
                ReportPropertyChanging("PasswordAnswerHash");
                _PasswordAnswerHash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordAnswerHash");
                OnPasswordAnswerHashChanged();
            }
        }
        private global::System.String _PasswordAnswerHash;
        partial void OnPasswordAnswerHashChanging(global::System.String value);
        partial void OnPasswordAnswerHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordAnswerSalt
        {
            get
            {
                return _PasswordAnswerSalt;
            }
            set
            {
                OnPasswordAnswerSaltChanging(value);
                ReportPropertyChanging("PasswordAnswerSalt");
                _PasswordAnswerSalt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordAnswerSalt");
                OnPasswordAnswerSaltChanged();
            }
        }
        private global::System.String _PasswordAnswerSalt;
        partial void OnPasswordAnswerSaltChanging(global::System.String value);
        partial void OnPasswordAnswerSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserType
        {
            get
            {
                return _UserType;
            }
            set
            {
                OnUserTypeChanging(value);
                ReportPropertyChanging("UserType");
                _UserType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserType");
                OnUserTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _UserType;
        partial void OnUserTypeChanging(Nullable<global::System.Int32> value);
        partial void OnUserTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProfileReset
        {
            get
            {
                return _ProfileReset;
            }
            set
            {
                OnProfileResetChanging(value);
                ReportPropertyChanging("ProfileReset");
                _ProfileReset = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfileReset");
                OnProfileResetChanged();
            }
        }
        private Nullable<global::System.Int32> _ProfileReset;
        partial void OnProfileResetChanging(Nullable<global::System.Int32> value);
        partial void OnProfileResetChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventoryManagementModel", Name="Vendor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vendor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vendor object.
        /// </summary>
        /// <param name="vendorID">Initial value of the VendorID property.</param>
        /// <param name="vendorName">Initial value of the VendorName property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="zip">Initial value of the Zip property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        /// <param name="contactPerson">Initial value of the ContactPerson property.</param>
        /// <param name="meansOfPayment">Initial value of the MeansOfPayment property.</param>
        public static Vendor CreateVendor(global::System.Int32 vendorID, global::System.String vendorName, global::System.String address, global::System.String city, global::System.String state, global::System.String zip, global::System.String email, global::System.String phoneNumber, global::System.String contactPerson, global::System.Int32 meansOfPayment)
        {
            Vendor vendor = new Vendor();
            vendor.VendorID = vendorID;
            vendor.VendorName = vendorName;
            vendor.Address = address;
            vendor.City = city;
            vendor.State = state;
            vendor.Zip = zip;
            vendor.Email = email;
            vendor.PhoneNumber = phoneNumber;
            vendor.ContactPerson = contactPerson;
            vendor.MeansOfPayment = meansOfPayment;
            return vendor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                if (_VendorID != value)
                {
                    OnVendorIDChanging(value);
                    ReportPropertyChanging("VendorID");
                    _VendorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VendorID");
                    OnVendorIDChanged();
                }
            }
        }
        private global::System.Int32 _VendorID;
        partial void OnVendorIDChanging(global::System.Int32 value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VendorName
        {
            get
            {
                return _VendorName;
            }
            set
            {
                OnVendorNameChanging(value);
                ReportPropertyChanging("VendorName");
                _VendorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VendorName");
                OnVendorNameChanged();
            }
        }
        private global::System.String _VendorName;
        partial void OnVendorNameChanging(global::System.String value);
        partial void OnVendorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContactPerson
        {
            get
            {
                return _ContactPerson;
            }
            set
            {
                OnContactPersonChanging(value);
                ReportPropertyChanging("ContactPerson");
                _ContactPerson = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContactPerson");
                OnContactPersonChanged();
            }
        }
        private global::System.String _ContactPerson;
        partial void OnContactPersonChanging(global::System.String value);
        partial void OnContactPersonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeansOfPayment
        {
            get
            {
                return _MeansOfPayment;
            }
            set
            {
                OnMeansOfPaymentChanging(value);
                ReportPropertyChanging("MeansOfPayment");
                _MeansOfPayment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MeansOfPayment");
                OnMeansOfPaymentChanged();
            }
        }
        private global::System.Int32 _MeansOfPayment;
        partial void OnMeansOfPaymentChanging(global::System.Int32 value);
        partial void OnMeansOfPaymentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Commodity__Vendo__24927208", "Commodity")]
        public EntityCollection<Commodity> Commodities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commodity>("InventoryManagementModel.FK__Commodity__Vendo__24927208", "Commodity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commodity>("InventoryManagementModel.FK__Commodity__Vendo__24927208", "Commodity", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventoryManagementModel", "FK__Vendor__MeansOfP__15502E78", "MeansOfPayment")]
        public MeansOfPayment MeansOfPayment1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MeansOfPayment>("InventoryManagementModel.FK__Vendor__MeansOfP__15502E78", "MeansOfPayment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MeansOfPayment>("InventoryManagementModel.FK__Vendor__MeansOfP__15502E78", "MeansOfPayment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MeansOfPayment> MeansOfPayment1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MeansOfPayment>("InventoryManagementModel.FK__Vendor__MeansOfP__15502E78", "MeansOfPayment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MeansOfPayment>("InventoryManagementModel.FK__Vendor__MeansOfP__15502E78", "MeansOfPayment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventoryManagementModel", Name="WorkOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkOrder object.
        /// </summary>
        /// <param name="workOrderID">Initial value of the WorkOrderID property.</param>
        public static WorkOrder CreateWorkOrder(global::System.Int32 workOrderID)
        {
            WorkOrder workOrder = new WorkOrder();
            workOrder.WorkOrderID = workOrderID;
            return workOrder;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkOrderID
        {
            get
            {
                return _WorkOrderID;
            }
            set
            {
                if (_WorkOrderID != value)
                {
                    OnWorkOrderIDChanging(value);
                    ReportPropertyChanging("WorkOrderID");
                    _WorkOrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkOrderID");
                    OnWorkOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _WorkOrderID;
        partial void OnWorkOrderIDChanging(global::System.Int32 value);
        partial void OnWorkOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JobID
        {
            get
            {
                return _JobID;
            }
            set
            {
                OnJobIDChanging(value);
                ReportPropertyChanging("JobID");
                _JobID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JobID");
                OnJobIDChanged();
            }
        }
        private global::System.String _JobID;
        partial void OnJobIDChanging(global::System.String value);
        partial void OnJobIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JobStatus
        {
            get
            {
                return _JobStatus;
            }
            set
            {
                OnJobStatusChanging(value);
                ReportPropertyChanging("JobStatus");
                _JobStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JobStatus");
                OnJobStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _JobStatus;
        partial void OnJobStatusChanging(Nullable<global::System.Int32> value);
        partial void OnJobStatusChanged();

        #endregion
    
    }

    #endregion
    
}
